name:                Lessons
version:             0.1.0.0
# github:              kapkekes
license:             BSD3
author:              Dmitriy Vashurin
maintainer:          kapkekes@yandex.ru
copyright:           2021 Dmitriy Vashurin
synopsis:            Homework
category:            Educational

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/kapkekes/Lessons#readme>

dependencies:
- base        >= 4.7      && < 5
- pcre-heavy  >= 1.0.0.2
- text        >= 1.2.4.1
- directory   >= 1.3.6.0
- iconv       >= 0.4.1.3
- bytestring
# Project contains builded "iconv" in ".stack-work" folder an source code
# in "packages/iconv-0.4.1.3". If you want to try to build it yourself,
# please, execute "stack clean" before to clean builded version.
# (Stack won't build the module, if it can find already builded version)

library:
  source-dirs:           source

executables:
  Task-1:
    main:                Main.hs
    source-dirs:         application/Task-1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
  Task-2:
    main:                Main.hs
    source-dirs:         application/Task-2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
  Task-3:
    main:                Main.hs
    source-dirs:         application/Task-3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
  Task-4:
    main:                Main.hs
    source-dirs:         application/Task-4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
  Task-5:
    main:                Main.hs
    source-dirs:         application/Task-5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons

tests:
  Lessons-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
