name:                Lessons
version:             0.1.0.0
# github:              kapkekes
license:             BSD3
author:              Dmitriy Vashurin
maintainer:          kapkekes@yandex.ru
copyright:           2022 Dmitriy Vashurin
synopsis:            Homework
category:            Educational

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/kapkekes/Lessons#readme>

dependencies:
- base        >= 4.7      && < 5
- mtl         >= 2.0.0
- array       >= 0.5.0.0
- containers  >= 0.6.0.0
- lens        >= 5.0
- dequeue

library:
  source-dirs:           source
