name:                Lessons
version:             0.1.0.0
# github:              kapkekes
license:             BSD3
author:              Dmitriy Vashurin
maintainer:          kapkekes@yandex.ru
copyright:           2021 Dmitriy Vashurin
synopsis:            Homework
category:            Educational

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/kapkekes/Lessons#readme>

dependencies:
- base >= 4.7 && < 5
- pcre-heavy >= 1.0.0.2
- text >= 1.2.4.1
- directory >= 1.3.6.0
- bytestring
# Project contains builded "iconv" in ".stack-work" folder an source code
# in "packages/iconv-0.4.1.3". If you want to try to build it yourself,
# please, execute "stack clean" before to clean builded version.
# (Stack won't build the module, if it can find already builded version)
# - iconv >= 0.4.1.3

library:
  source-dirs:           source

executables:
  First:
    main:                First.hs
    source-dirs:         application
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is First
    dependencies:
    - Lessons
  Second:
    main:                Second.hs
    source-dirs:         application
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Second
    dependencies:
    - Lessons
  Third:
    main:                Third.hs
    source-dirs:         application
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Third
    dependencies:
    - Lessons

tests:
  Lessons-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
