name:                Lessons
version:             0.1.0.0
# github:              kapkekes
license:             WTFPL
author:              Dmitriy Vashurin
maintainer:          kapkekes@yandex.ru
copyright:           2021 Dmitriy Vashurin

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kapkekes/Lessons#readme>

dependencies:
- base >= 4.7 && < 5
- pcre-heavy >= 1.0.0.2
- text >= 1.2.4.1
- iconv >= 0.4.1.3
- directory >= 1.3.6.0
- bytestring

library:
  source-dirs:           source

executables:
  Lessons-exe:
    main:                Main.hs
    source-dirs:         application
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons

tests:
  Lessons-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lessons
